output_directory: /localdata/juan/iros2018/corkscrew6legs/

default_task_params: &default_task_params
  initial_random_trials: 5
  random_exp_path: /localdata/juan/iros2018/rnd_experience6_dt_0_5.zip
  n_opt: 50
  horizon_secs: 20.0
  discount: 1.0
  angle_dims: &default_angle_dims [0, 1, 2]
  random_walk: True
  wrap_angles: True
  return_best: False
  n_samples: 500
  learning_rate: !numpy 1e-4
  # options for truncated backpropagation through time
  # split the horizon in split_H segments and, for each segment, remove
  # truncate_gradient time steps from the beginning of the sequence
  # (during the backwards pass)
  split_H: 1
  truncate_gradient: 0
  crn: 200
  mm_cost: True
  mm_state: True
  noisy_policy_input: True

default_policy_params: &default_policy_params
  input_dims: 13  # TODO, this should be inferred from data
  angle_dims: *default_angle_dims
  maxU: !numpy "[np.pi/4]*6 + [np.pi/3]*6 + [np.pi]*6"
  minU: !numpy "[0]*6 + [-np.pi/3]*6 + [-np.pi]*6"
  sat_func: !!python/name:kusanagi.ghost.control.saturation.tanhSat

default_bnn_params: &default_bnn_params
  # TODO, these dimensions should be inferred from data
  idims: 34 # non_angle_state_dims + 2*angle_state_dims + controls
  odims: 13 # state_dims
  max_evals: 4000 # max evals for optimizer (.train() method)  

default_network_spec: &default_network_spec
  hidden_dims: !numpy '[200]*4'
  p: 0.25
  p_input: 0.0
  nonlinearities: !!python/name:kusanagi.ghost.regression.nonlinearities.rectify
  W_init: !!python/object/apply:lasagne.init.Orthogonal {}
  dropout_class: !!python/name:kusanagi.ghost.regression.layers.DenseDropoutLayer
  build_fn: !!python/name:kusanagi.ghost.regression.dropout_mlp

default_plant: &default_plant_params
    dt: 0.5
    state0_dist: &state0_dist !!python/object/apply:kusanagi.utils.distributions.Gaussian
      kwds: &state0_dist_kwds
        mean: !numpy np.array([0.0, 0.0, 0.0,
                               1.0,
                               0.0, 0.0, 0.0,
                               0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        cov: !numpy np.eye(13)*(0.2**2)
    name: 'AquaRobotEnv'

default_loss_graph: &default_loss_graph !!python/object/apply:functools.partial
  func_: &func_ !!python/name:kusanagi.shell.cost.distance_based_cost
  args: [*func_]
  kwds:  
    loss_func: !!python/name:kusanagi.shell.cost.quadratic_saturating_loss
    cw: !numpy 0.15*np.pi/3
    expl: 0.0

default_loss_fn: &default_loss_fn !!python/object/apply:kusanagi.shell.cost.build_loss_func
  args: [*default_loss_graph]
  kwds: &default_loss_fn_params
    angle_dims: !!python/object/apply:theano.tensor.ivector ['angle_dims']
    target: !!python/object/apply:theano.tensor.vector ['target']
    Q: !!python/object/apply:theano.tensor.matrix ['Q']

default_Q: 
  angle:   &angle_Q !numpy np.diag([1.0, 0.0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]) # Use this for angle-stabilization tasks
  roll: &rollrate_Q !numpy np.diag([1.0, 1.0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0]) # Use this for fixed roll-rate tasks 

tasks:
   corkscrew6:
    <<: *default_task_params
    cost:
      params: &cs_cost_params
        angle_dims: *default_angle_dims
        target: !numpy "[0, 0, 0, 1.0, np.pi/3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
        Q: *rollrate_Q
      fn: &cs_cost !!python/object/apply:functools.partial
        args: [*default_loss_fn]
        kwds:
          <<: *cs_cost_params
      graph: !!python/object/apply:functools.partial
        args: [*default_loss_graph]
        kwds:
          <<: *cs_cost_params
    policy: !!python/object/apply:kusanagi.ghost.control.NNPolicy
      kwds:
        <<: *default_policy_params
        network_spec:
          <<: *default_network_spec
    transition_model: !!python/object/apply:kusanagi.ghost.regression.BNN
      kwds:
        <<: *default_bnn_params
        network_spec:
          <<: *default_network_spec
          p_input: 0.1
          dropout_class: !!python/name:kusanagi.ghost.regression.layers.DenseLogNormalDropoutLayer
    plant:
      <<: *default_plant_params
      loss_func: *cs_cost
    optimizer: !!python/object/apply:kusanagi.ghost.optimizers.SGDOptimizer
        kwds:
          min_method: 'ADAM'
          max_evals: 500
